In [ ]:
import pandas as pd
import numpy as np

In [ ]:
bank = pd.read_csv('https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Bank%20Tele%20Marketing/bank_market.csv')

In [ ]:
two_col = np.array(bank[["age", "Cust_num", "balance", "loan"]])
print(two_col)
print('shape =' + str(two_col.shape))
print('dimensions =' + str(two_col.ndim))
print('data type =' + str(two_col.dtype))
print('size =' + str(two_col.size))


In [ ]:
print((bank))
print('shape =' + str(bank.shape))
print('dimensions =' + str(bank.ndim))
print('data type =' + str(bank.dtypes))
print('size =' + str(bank.size))


In [39]:
two_vars = ['age','balance']
two_col = np.array(bank[two_vars])
print(two_col)

[[  58 2143]
 [  44   29]
 [  33    2]
 ...
 [  72 5715]
 [  57  668]
 [  37 2971]]


In [62]:
print(two_col[:,:])

[[  58 2143]
 [  44   29]
 [  33    2]
 ...
 [  72 5715]
 [  57  668]
 [  37 2971]]


In [71]:
age_var = np.array(bank['age'])
con1 = age_var > 60
print(con1)

[False False False ...  True False False]


In [72]:
print(con1)

[False False False ...  True False False]


In [73]:
print(con1 == True)

[False False False ...  True False False]


In [80]:
newage_var = age_var[con1==False]

In [81]:
print(newage_var)

[58 44 33 ... 51 57 37]


In [82]:
print(newage_var.size)

44023


Accessing Arrays project

In [83]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [111]:
b = a[0:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [112]:
b[0,0] = 100
print(b)


[[100   3]
 [  6   7]]


In [113]:
print(a)

[[  1 100   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
